# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJgW258k64vcH5hO3NeO-dy8R5nLFADZ

#  Online Courses EDA — Coursera · Udemy · Skillshare
**Datasets:**
- `azrai99/coursera-course-dataset` (HuggingFace)
- `khaledatef1/online-courses` (Kaggle / Udemy)
- `everydaycodings/multi-platform-online-courses-dataset` → `skillshare.csv` (Kaggle)
"""

! pip install -q datasets kaggle pandas numpy matplotlib seaborn plotly scipy

# ── HuggingFace: Coursera ──────────────────────────────────────────────────
from datasets import load_dataset
import pandas as pd
import numpy as np

hf_ds = load_dataset("azrai99/coursera-course-dataset")
coursera = hf_ds["train"].to_pandas()
print("Coursera shape:", coursera.shape)
coursera.head(3)

# ── Kaggle: Udemy courses (khaledatef1/online-courses) ────────────────────
!kaggle datasets download -d khaledatef1/online-courses --unzip -p /content/udemy_data
import os
print(os.listdir('/content/udemy_data'))

udemy_files = os.listdir('/content/udemy_data')
udemy_csv   = [f for f in udemy_files if f.endswith('.csv')][0]
udemy = pd.read_csv(f'/content/udemy_data/{udemy_csv}')
print("Udemy shape:", udemy.shape)
udemy.head(3)

# ── Kaggle: Skillshare (everydaycodings/multi-platform-online-courses-dataset) ──
!kaggle datasets download -d everydaycodings/multi-platform-online-courses-dataset --unzip -p /content/skillshare_data
print(os.listdir('/content/skillshare_data'))

skillshare = pd.read_csv('/content/skillshare_data/skillshare.csv')
print("Skillshare shape:", skillshare.shape)
skillshare.head(3)

# ── Check all dataset columns ─────────────────────────────────────────────

datasets = [
    (coursera, 'Coursera'),
    (udemy, 'Udemy'),
    (skillshare, 'Skillshare')
]

for df, name in datasets:

    print(f"\n{'='*60}")
    print(f"{name} DATASET")
    print(f"{'='*60}")

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nSample Data:")
    display(df.head())

"""#Basic info and Cleaning"""

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# ── Global style ────────────────────────────────────────────────────────────
plt.rcParams.update({
    'figure.facecolor': '#0f1117',
    'axes.facecolor':   '#1a1d27',
    'axes.edgecolor':   '#2e3347',
    'axes.labelcolor':  '#c9cdd4',
    'xtick.color':      '#c9cdd4',
    'ytick.color':      '#c9cdd4',
    'text.color':       '#e0e3ea',
    'grid.color':       '#2e3347',
    'grid.linestyle':   '--',
    'grid.alpha':        0.5,
    'font.family':      'DejaVu Sans',
    'axes.titlesize':    14,
    'axes.labelsize':    11,
})

PAL  = ['#4c7ef3', '#f07c3a', '#2fc09e', '#a97edd', '#e85c6e', '#f5c842', '#56c9f5', '#85d454']
BLUE, ORANGE, GREEN, PURPLE = PAL[0], PAL[1], PAL[2], PAL[3]

def title(ax, t, sub=None):
    ax.set_title(t, fontsize=13, fontweight='bold', pad=10)
    if sub:
        ax.set_title(sub, fontsize=10, color='#888', loc='right')

print("Libraries loaded ")

#Column Helper
print("=== COURSERA COLUMNS ===", coursera.columns.tolist())
print("\n=== UDEMY COLUMNS ===",   udemy.columns.tolist())
print("\n=== SKILLSHARE COLUMNS ===", skillshare.columns.tolist())

# ── Standardise key column names ───────────────────────────────────────────
# Coursera — map to common names
COURSERA_MAP = {
    'Course Name':  'title',
    'Category':     'category',
    'Level':        'level',
    'Institution':  'institution',
    'Duration':     'duration',
    'Rating':       'rating',
    'Reviews':      'num_reviews',
    'Students':     'enrolled',
}
coursera.rename(columns={k:v for k,v in COURSERA_MAP.items() if k in coursera.columns}, inplace=True)

# Udemy
UDEMY_MAP = {
    'course_title':       'title',
    'subject':            'subject',
    'is_paid':            'is_paid',
    'price':              'price',
    'num_subscribers':    'num_subscribers',
    'num_reviews':        'num_reviews',
    'num_lectures':       'num_lectures',
    'level':              'level',
    'content_duration':   'hours',
    'published_timestamp':'published_at',
    'rating':             'rating',
}
udemy.rename(columns={k:v for k,v in UDEMY_MAP.items() if k in udemy.columns}, inplace=True)

# Skillshare
SKILLSHARE_MAP = {
    'Title':          'title',
    'Category':       'category',
    'Students':       'num_students',
    'Projects':       'num_projects',
    'Lessons':        'num_lessons',
    'Duration':       'duration_min',
    'Rating':         'rating',
    'Premium':        'is_premium',
}
skillshare.rename(columns={k:v for k,v in SKILLSHARE_MAP.items() if k in skillshare.columns}, inplace=True)

# Numeric coercions
for df, cols in [
    (coursera,  ['rating','num_reviews','enrolled']),
    (udemy,     ['rating','price','num_subscribers','num_reviews','num_lectures','hours']),
    (skillshare,['rating','num_students','num_projects','num_lessons']),
]:
    for c in cols:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors='coerce')

print("Cleaning done ✓")
print(f"Rows — Coursera: {len(coursera):,}  |  Udemy: {len(udemy):,}  |  Skillshare: {len(skillshare):,}")

# ── Standardize Columns ───────────────────────────────────────────────────

# ---------- Udemy Dataset ----------

udemy.columns = (
    udemy.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

udemy.rename(columns={
    'category': 'category',
    'rating': 'rating',
    'duration': 'duration',
    'number_of_reviews': 'num_reviews',
    'number_of_viewers': 'num_students',
    'price': 'price',
    'level': 'level'
}, inplace=True)

# Convert numeric columns safely
for col in ['rating', 'num_reviews', 'price']:

    if col in udemy.columns:

        udemy[col] = pd.to_numeric(
            udemy[col],
            errors='coerce'
        )

# ---------- Skillshare Dataset ----------

skillshare.columns = (
    skillshare.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

# Extract numeric students
if 'students' in skillshare.columns:

    skillshare['students_count'] = (
        skillshare['students']
        .str.replace(' students', '', regex=False)
        .str.replace(',', '', regex=False)
    )

    skillshare['students_count'] = pd.to_numeric(
        skillshare['students_count'],
        errors='coerce'
    )

# Convert duration into minutes
if 'duration' in skillshare.columns:

    def convert_duration(x):

        if pd.isna(x):
            return np.nan

        x = str(x).lower()

        hours = 0
        mins = 0

        if 'h' in x:
            try:
                hours = int(x.split('h')[0].strip())
            except:
                pass

        if 'm' in x:
            try:
                mins = int(
                    x.split('h')[-1]
                    .replace('m', '')
                    .strip()
                )
            except:
                pass

        return hours * 60 + mins

    skillshare['duration_min'] = skillshare['duration'].apply(convert_duration)

print("Udemy Columns:")
print(udemy.columns.tolist())

print("\nSkillshare Columns:")
print(skillshare.columns.tolist())

# ── Missing values heatmap ─────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 4))
for ax, (df, name) in zip(axes, [(coursera,'Coursera'),(udemy,'Udemy'),(skillshare,'Skillshare')]):
    miss = df.isnull().mean().sort_values(ascending=False)
    miss = miss[miss > 0] if miss.any() else miss.head(8)
    colors = [BLUE if v < 0.05 else ORANGE if v < 0.20 else '#e85c6e' for v in miss.values]
    ax.barh(miss.index, miss.values * 100, color=colors)
    ax.set_xlabel('Missing %')
    ax.set_title(f'{name} — Missing Values', fontweight='bold')
    ax.axvline(5,  color='#f5c842', lw=1, ls='--', alpha=0.7, label='5%')
    ax.axvline(20, color='#e85c6e', lw=1, ls='--', alpha=0.7, label='20%')
    ax.legend(fontsize=8)
plt.tight_layout(); plt.show()

"""#Platform Overview"""

# ── 3.1  Course count & average rating by platform ─────────────────────────
summary = pd.DataFrame({
    'Platform':    ['Coursera', 'Udemy', 'Skillshare'],
    'Courses':     [len(coursera), len(udemy), len(skillshare)],
    'Avg Rating':  [
        coursera['rating'].mean() if 'rating' in coursera.columns else 0,
        udemy['rating'].mean()    if 'rating' in udemy.columns    else 0,
        skillshare['rating'].mean() if 'rating' in skillshare.columns else 0,
    ]
})

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

bars = ax1.bar(summary['Platform'], summary['Courses'], color=PAL[:3], width=0.5, zorder=2)
for bar, val in zip(bars, summary['Courses']):
    ax1.text(bar.get_x()+bar.get_width()/2, bar.get_height()+30,
             f'{val:,}', ha='center', va='bottom', fontsize=11, fontweight='bold')
ax1.set_title('Course Count by Platform', fontweight='bold'); ax1.set_ylabel('Courses'); ax1.grid(axis='y', zorder=1)

bars2 = ax2.bar(summary['Platform'], summary['Avg Rating'], color=PAL[:3], width=0.5, zorder=2)
for bar, val in zip(bars2, summary['Avg Rating']):
    ax2.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.01,
             f'{val:.2f}', ha='center', va='bottom', fontsize=11, fontweight='bold')
ax2.set_ylim(0, 5); ax2.set_title('Average Rating by Platform', fontweight='bold')
ax2.set_ylabel('Avg Rating'); ax2.grid(axis='y', zorder=1)

plt.tight_layout(); plt.show()

# ── 3.2  Rating distribution — KDE overlay (all 3 platforms) ──────────────
fig, ax = plt.subplots(figsize=(12, 5))

for df, name, color in [
    (coursera,  'Coursera',   BLUE),
    (udemy,     'Udemy',      ORANGE),
    (skillshare,'Skillshare', GREEN),
]:
    if 'rating' in df.columns:
        data = df['rating'].dropna()
        ax.hist(data, bins=30, density=True, alpha=0.25, color=color)
        kde_x = np.linspace(data.min(), data.max(), 300)
        kde   = stats.gaussian_kde(data)(kde_x)
        ax.plot(kde_x, kde, color=color, lw=2.5, label=f'{name} (μ={data.mean():.2f})')
        ax.axvline(data.mean(), color=color, lw=1.2, ls='--', alpha=0.7)

ax.set_xlabel('Rating'); ax.set_ylabel('Density')
ax.set_title('Rating Distribution — All Platforms', fontweight='bold')
ax.legend(); ax.grid(True, alpha=0.3)
plt.tight_layout(); plt.show()

"""#Coursera Deep Dive"""

# ── 4.1 Category breakdown ────────────────────────────────────────────────

# Check available columns
print(udemy.columns.tolist())

# Category counts
cat_counts = (
    udemy['category']
    .dropna()
    .astype(str)
    .str.strip()
    .value_counts()
    .head(10)
)

# Create figure
fig, (ax1, ax2) = plt.subplots(
    1,
    2,
    figsize=(16, 6)
)

# ── Horizontal Bar Chart ─────────────────────

colors = plt.cm.Blues(
    np.linspace(0.4, 0.9, len(cat_counts))[::-1]
)

bars = ax1.barh(
    cat_counts.index,
    cat_counts.values,
    color=colors
)

# Labels on bars
for bar, val in zip(bars, cat_counts.values):

    ax1.text(
        bar.get_width() + 1,
        bar.get_y() + bar.get_height()/2,
        str(val),
        va='center',
        fontsize=9
    )

ax1.set_xlabel('Number of Courses')

ax1.set_title(
    'Udemy — Courses per Category',
    fontweight='bold'
)

ax1.invert_yaxis()
ax1.grid(axis='x', alpha=0.3)

# ── Donut Chart ─────────────────────────────

donut_colors = plt.cm.Set3(
    np.linspace(0, 1, len(cat_counts))
)

wedges, texts, autotexts = ax2.pie(
    cat_counts.values,
    labels=cat_counts.index,
    autopct='%1.1f%%',
    colors=donut_colors,
    pctdistance=0.82,
    startangle=90,
    wedgeprops=dict(
        width=0.55,
        edgecolor='white',
        linewidth=1.5
    )
)

# Smaller percentage text
for t in autotexts:
    t.set_fontsize(8)

ax2.set_title(
    'Udemy — Category Share (Donut)',
    fontweight='bold'
)

plt.tight_layout()
plt.show()

# ── 4.2 Level & Duration ─────────────────────────────────────────────────

fig, axes = plt.subplots(
    1,
    2,
    figsize=(14, 5)
)

plots = [
    (axes[0], 'level', 'Level'),
    (axes[1], 'duration', 'Duration')
]

for ax, col, label in plots:

    # Check column exists
    if col in udemy.columns:

        # Clean values
        vc = (
            udemy[col]
            .dropna()
            .astype(str)
            .str.strip()
            .value_counts()
            .head(10)
        )

        # If no values
        if vc.empty:

            ax.text(
                0.5,
                0.5,
                'No Data',
                ha='center',
                va='center',
                fontsize=12
            )

            ax.axis('off')
            continue

        # Colors
        pie_colors = plt.cm.Set3(
            np.linspace(0, 1, len(vc))
        )

        # Pie chart
        ax.pie(
            vc.values,
            labels=vc.index,
            autopct='%1.1f%%',
            colors=pie_colors,
            startangle=90,
            wedgeprops=dict(
                edgecolor='white',
                linewidth=1.5
            )
        )

        ax.set_title(
            f'Udemy — {label} Distribution',
            fontweight='bold'
        )

    else:

        ax.text(
            0.5,
            0.5,
            f'{col} column missing',
            ha='center',
            va='center',
            fontsize=12
        )

        ax.axis('off')

plt.tight_layout()
plt.show()

# ── 4.3 Average enrollment by category ───────────────────────────────────

required_cols = {'category', 'num_students'}

if required_cols.issubset(udemy.columns):

    # Clean numeric values
    udemy['num_students'] = pd.to_numeric(
        udemy['num_students'],
        errors='coerce'
    )

    # Remove missing rows
    temp_df = udemy.dropna(
        subset=['category', 'num_students']
    )

    # Group by category
    enroll_cat = (
        temp_df
        .groupby('category')['num_students']
        .mean()
        .sort_values(ascending=True)
        .tail(10)
    )

    # Create figure
    fig, ax = plt.subplots(figsize=(12, 6))

    colors = plt.cm.viridis(
        np.linspace(0.3, 0.9, len(enroll_cat))
    )

    bars = ax.barh(
        enroll_cat.index,
        enroll_cat.values,
        color=colors
    )

    # Labels
    for bar, val in zip(bars, enroll_cat.values):

        ax.text(
            bar.get_width() + 200,
            bar.get_y() + bar.get_height()/2,
            f'{val:,.0f}',
            va='center',
            fontsize=9
        )

    ax.set_xlabel('Average Enrollment')

    ax.set_title(
        'Udemy — Average Enrollment per Category',
        fontweight='bold'
    )

    ax.grid(axis='x', alpha=0.3)

    plt.tight_layout()
    plt.show()

else:

    print("Required columns missing")

# ── 4.4  Rating vs Reviews scatter (Coursera) ──────────────────────────────
if {'rating','num_reviews'}.issubset(coursera.columns):
    sample = coursera.dropna(subset=['rating','num_reviews']).sample(min(500, len(coursera)), random_state=42)

    fig, ax = plt.subplots(figsize=(10, 6))
    sc = ax.scatter(sample['rating'], sample['num_reviews'],
                    c=sample['rating'], cmap='plasma',
                    alpha=0.55, s=40, edgecolors='none')
    plt.colorbar(sc, ax=ax, label='Rating')

    # Regression line
    m, b, r, p, _ = stats.linregress(sample['rating'], sample['num_reviews'])
    x_line = np.linspace(sample['rating'].min(), sample['rating'].max(), 100)
    ax.plot(x_line, m*x_line+b, color=ORANGE, lw=2, label=f'OLS  r={r:.2f}, p={p:.3f}')

    ax.set_xlabel('Rating'); ax.set_ylabel('Number of Reviews')
    ax.set_title('Coursera — Rating vs. Number of Reviews', fontweight='bold')
    ax.legend(); ax.grid(True, alpha=0.3)
    plt.tight_layout(); plt.show()

# ── 4.5  Box plot: rating by level (Coursera) ─────────────────────────────
if {'level','rating'}.issubset(coursera.columns):
    levels = coursera['level'].dropna().unique().tolist()
    data_by_level = [coursera[coursera['level']==l]['rating'].dropna().values for l in levels]

    fig, ax = plt.subplots(figsize=(10, 5))
    bp = ax.boxplot(data_by_level, labels=levels, patch_artist=True, notch=True,
                    medianprops=dict(color='white', lw=2))
    for patch, color in zip(bp['boxes'], PAL):
        patch.set_facecolor(color); patch.set_alpha(0.7)
    ax.set_ylabel('Rating')
    ax.set_title('Coursera — Rating Distribution by Level', fontweight='bold')
    ax.grid(axis='y', alpha=0.3)
    plt.tight_layout(); plt.show()

"""#Udemy Deep Dive"""

# ── 5.1 Students by category ─────────────────────────────────────────────

required_cols = {'category', 'num_students'}

if required_cols.issubset(udemy.columns):

    # Convert to numeric
    udemy['num_students'] = pd.to_numeric(
        udemy['num_students'],
        errors='coerce'
    )

    # Remove missing rows
    temp_df = udemy.dropna(
        subset=['category', 'num_students']
    )

    # Group data
    sub_enroll = (
        temp_df
        .groupby('category')['num_students']
        .mean()
        .sort_values(ascending=False)
        .head(10)
    )

    # Create figure
    fig, ax = plt.subplots(
        figsize=(12, 6)
    )

    colors = plt.cm.Oranges(
        np.linspace(0.4, 0.9, len(sub_enroll))[::-1]
    )

    bars = ax.bar(
        sub_enroll.index,
        sub_enroll.values,
        color=colors,
        zorder=2
    )

    # Labels
    for bar, val in zip(bars, sub_enroll.values):

        ax.text(
            bar.get_x() + bar.get_width()/2,
            bar.get_height() + 100,
            f'{val:,.0f}',
            ha='center',
            va='bottom',
            fontsize=8,
            rotation=45
        )

    ax.set_xticks(range(len(sub_enroll.index)))
    ax.set_xticklabels(
        sub_enroll.index,
        rotation=30,
        ha='right'
    )

    ax.set_ylabel('Average Students')

    ax.set_title(
        'Udemy — Average Students per Category',
        fontweight='bold'
    )

    ax.grid(
        axis='y',
        alpha=0.3,
        zorder=1
    )

    plt.tight_layout()
    plt.show()

else:

    print("Required columns missing")

# ── 5.2 Price distribution histogram ────────────────────────────────────

if 'price' in udemy.columns:

    # Convert safely to numeric
    udemy['price'] = pd.to_numeric(
        udemy['price'],
        errors='coerce'
    )

    # Keep paid courses only
    paid = udemy[
        udemy['price'] > 0
    ]['price'].dropna()

    # Check data exists
    if len(paid) == 0:

        print("No paid course price data available")

    else:

        # Create figure
        fig, ax = plt.subplots(
            figsize=(12, 5)
        )

        ax.hist(
            paid,
            bins=40,
            color=ORANGE,
            alpha=0.8,
            edgecolor='black',
            lw=0.4
        )

        # Median line
        ax.axvline(
            paid.median(),
            color='white',
            lw=1.5,
            ls='--',
            label=f'Median ${paid.median():.0f}'
        )

        # Mean line
        ax.axvline(
            paid.mean(),
            color=BLUE,
            lw=1.5,
            ls='--',
            label=f'Mean ${paid.mean():.0f}'
        )

        ax.set_xlabel('Price (USD)')
        ax.set_ylabel('Count')

        ax.set_title(
            'Udemy — Paid Course Price Distribution',
            fontweight='bold'
        )

        ax.legend()
        ax.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

else:

    print("'price' column missing")

# ── 5.3 Free vs Paid courses by category ────────────────────────────────

required_cols = {'category', 'price', 'num_students'}

if required_cols.issubset(udemy.columns):

    # Convert numeric columns
    udemy['price'] = pd.to_numeric(
        udemy['price'],
        errors='coerce'
    )

    udemy['num_students'] = pd.to_numeric(
        udemy['num_students'],
        errors='coerce'
    )

    # Create paid/free column
    udemy['is_paid'] = np.where(
        udemy['price'] > 0,
        'Paid',
        'Free'
    )

    # Remove missing rows
    temp_df = udemy.dropna(
        subset=['category', 'num_students']
    )

    # Group data
    pivot_fp = (
        temp_df
        .groupby(['category', 'is_paid'])['num_students']
        .mean()
        .unstack(fill_value=0)
    )

    # Keep top categories only
    pivot_fp = pivot_fp.head(10)

    # Create figure
    fig, ax = plt.subplots(
        figsize=(13, 6)
    )

    pivot_fp.plot(
        kind='bar',
        stacked=True,
        ax=ax,
        color=[GREEN, ORANGE],
        width=0.65
    )

    ax.set_xticklabels(
        pivot_fp.index,
        rotation=30,
        ha='right'
    )

    ax.set_ylabel('Average Students')

    ax.set_title(
        'Udemy — Free vs Paid Average Students by Category',
        fontweight='bold'
    )

    ax.legend(title='Course Type')

    ax.grid(
        axis='y',
        alpha=0.3
    )

    plt.tight_layout()
    plt.show()

else:

    print("Required columns missing")

# ── 5.4 Course volume & average rating by category ──────────────────────

required_cols = {'category', 'rating'}

if required_cols.issubset(udemy.columns):

    # Convert rating to numeric
    udemy['rating'] = pd.to_numeric(
        udemy['rating'],
        errors='coerce'
    )

    # Remove missing rows
    temp_df = udemy.dropna(
        subset=['category', 'rating']
    )

    # Group data
    summary = (
        temp_df
        .groupby('category')
        .agg(
            course_count=('title', 'count'),
            avg_rating=('rating', 'mean')
        )
        .sort_values(
            by='course_count',
            ascending=False
        )
        .head(10)
    )

    # Create figure
    fig, ax1 = plt.subplots(
        figsize=(12, 5)
    )

    # Bar chart
    ax1.bar(
        summary.index,
        summary['course_count'],
        color=ORANGE,
        alpha=0.6,
        label='Courses'
    )

    ax1.set_xlabel('Category')

    ax1.set_ylabel(
        'Course Count',
        color=ORANGE
    )

    ax1.tick_params(
        axis='y',
        labelcolor=ORANGE
    )

    ax1.set_xticklabels(
        summary.index,
        rotation=30,
        ha='right'
    )

    # Second axis
    ax2 = ax1.twinx()

    ax2.plot(
        summary.index,
        summary['avg_rating'],
        color=BLUE,
        lw=2.5,
        marker='o',
        label='Average Rating'
    )

    ax2.set_ylabel(
        'Average Rating',
        color=BLUE
    )

    ax2.tick_params(
        axis='y',
        labelcolor=BLUE
    )

    ax1.set_title(
        'Udemy — Course Volume & Average Rating by Category',
        fontweight='bold'
    )

    # Combined legend
    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()

    ax1.legend(
        lines1 + lines2,
        labels1 + labels2,
        loc='upper left'
    )

    ax1.grid(
        axis='y',
        alpha=0.3
    )

    plt.tight_layout()
    plt.show()

else:

    print("Required columns missing")

# ── Better duration parser ───────────────────────────────────────────────

import re

def convert_duration(x):

    if pd.isna(x):
        return np.nan

    x = str(x).lower()

    # Months
    month_match = re.search(r'(\d+)\s*month', x)

    if month_match:
        months = int(month_match.group(1))

        # Approximation:
        # 1 month ≈ 30 days × 2 study hours/day
        return months * 60

    # Weeks
    week_match = re.search(r'(\d+)\s*week', x)

    if week_match:
        weeks = int(week_match.group(1))
        return weeks * 14

    # Hours
    hour_match = re.search(r'(\d+)\s*h', x)

    mins_match = re.search(r'(\d+)\s*m', x)

    hours = int(hour_match.group(1)) if hour_match else 0
    mins  = int(mins_match.group(1)) if mins_match else 0

    return hours + mins / 60

# Apply conversion
udemy['hours'] = udemy['duration'].apply(convert_duration)

# Check results
print(
    udemy[['duration', 'hours']].head(10)
)

# ── 5.5 Content duration vs students ────────────────────────────────────

required_cols = {'hours', 'num_students'}

if required_cols.issubset(udemy.columns):

    # Remove missing values
    sample_df = udemy.dropna(
        subset=['hours', 'num_students']
    )

    # Remove impossible values
    sample_df = sample_df[
        (sample_df['hours'] > 0)
    ]

    # Sample safely
    sample_size = min(1500, len(sample_df))

    if sample_size < 10:

        print("Not enough valid data")

    else:

        sample_u = sample_df.sample(
            sample_size,
            random_state=1
        )

        # Create figure
        fig, (ax1, ax2) = plt.subplots(
            1,
            2,
            figsize=(16, 6)
        )

        # ── Scatter Plot ─────────────────────

        ax1.scatter(
            sample_u['hours'],
            sample_u['num_students'],
            alpha=0.3,
            s=15,
            color=ORANGE
        )

        # Regression line
        m, b, r, p, _ = stats.linregress(
            sample_u['hours'],
            sample_u['num_students']
        )

        xr = np.linspace(
            sample_u['hours'].min(),
            sample_u['hours'].max(),
            100
        )

        ax1.plot(
            xr,
            m * xr + b,
            color='white',
            lw=2,
            label=f'r = {r:.2f}'
        )

        ax1.set_xlabel('Content Duration (hours)')
        ax1.set_ylabel('Students')

        ax1.set_title(
            'Duration vs Students',
            fontweight='bold'
        )

        ax1.legend()
        ax1.grid(True, alpha=0.3)

        # ── Hexbin Plot ─────────────────────

        hb = ax2.hexbin(
            sample_u['hours'],
            sample_u['num_students'],
            gridsize=30,
            cmap='YlOrRd',
            mincnt=1
        )

        fig.colorbar(
            hb,
            ax=ax2,
            label='Count'
        )

        ax2.set_xlabel('Content Duration (hours)')
        ax2.set_ylabel('Students')

        ax2.set_title(
            'Duration vs Students (Hexbin Density)',
            fontweight='bold'
        )

        plt.tight_layout()
        plt.show()

else:

    print("Required columns missing")

# ── 5.6 Violin plot: students by course type ────────────────────────────

required_cols = {'course_type', 'num_students'}

if required_cols.issubset(udemy.columns):

    # Convert students column
    udemy['num_students'] = pd.to_numeric(
        udemy['num_students'],
        errors='coerce'
    )

    # Remove missing rows
    temp_df = udemy.dropna(
        subset=['course_type', 'num_students']
    )

    # Remove non-positive values
    temp_df = temp_df[
        temp_df['num_students'] > 0
    ]

    # Get unique course types
    course_types = (
        temp_df['course_type']
        .astype(str)
        .unique()
        .tolist()
    )

    # Prepare violin data
    data_l = [
        np.log1p(
            temp_df[
                temp_df['course_type'] == c
            ]['num_students'].values
        )
        for c in course_types
    ]

    # Create figure
    fig, ax = plt.subplots(
        figsize=(11, 5)
    )

    parts = ax.violinplot(
        data_l,
        positions=range(len(course_types)),
        showmedians=True,
        showextrema=False
    )

    # Colors
    violin_colors = plt.cm.Set3(
        np.linspace(0, 1, len(course_types))
    )

    for pc, color in zip(parts['bodies'], violin_colors):

        pc.set_facecolor(color)
        pc.set_alpha(0.6)

    parts['cmedians'].set_color('black')
    parts['cmedians'].set_linewidth(2)

    ax.set_xticks(
        range(len(course_types))
    )

    ax.set_xticklabels(
        course_types,
        rotation=20,
        ha='right'
    )

    ax.set_ylabel('log(1 + Students)')

    ax.set_title(
        'Udemy — Student Distribution by Course Type',
        fontweight='bold'
    )

    ax.grid(
        axis='y',
        alpha=0.3
    )

    plt.tight_layout()
    plt.show()

else:

    print("Required columns missing")

"""#Skillshare Deep Dive"""

# ── 6.1 Average students by instructor ──────────────────────────────────

required_cols = {'instructor', 'students_count'}

if required_cols.issubset(skillshare.columns):

    # Remove missing values
    temp_df = skillshare.dropna(
        subset=['instructor', 'students_count']
    )

    # Group by instructor
    instructor_avg = (
        temp_df
        .groupby('instructor')['students_count']
        .mean()
        .sort_values(ascending=True)
        .tail(10)
    )

    # Create figure
    fig, ax = plt.subplots(
        figsize=(11, 6)
    )

    colors = plt.cm.Greens(
        np.linspace(0.4, 0.9, len(instructor_avg))
    )

    bars = ax.barh(
        instructor_avg.index,
        instructor_avg.values,
        color=colors
    )

    # Labels
    for bar, val in zip(bars, instructor_avg.values):

        ax.text(
            bar.get_width() + 50,
            bar.get_y() + bar.get_height()/2,
            f'{val:,.0f}',
            va='center',
            fontsize=9
        )

    ax.set_xlabel('Average Students per Course')

    ax.set_title(
        'Skillshare — Average Students by Instructor',
        fontweight='bold'
    )

    ax.grid(
        axis='x',
        alpha=0.3
    )

    plt.tight_layout()
    plt.show()

else:

    print("Required columns missing")

# ── 6.2 Duration vs Students scatter ────────────────────────────────────

required_cols = {'duration_min', 'students_count'}

if required_cols.issubset(skillshare.columns):

    # Remove missing rows
    s = skillshare.dropna(
        subset=['duration_min', 'students_count']
    )

    # Remove invalid values
    s = s[
        (s['duration_min'] > 0) &
        (s['students_count'] > 0)
    ]

    # Sample safely
    sample_size = min(2000, len(s))

    if sample_size < 10:

        print("Not enough valid data")

    else:

        s = s.sample(
            sample_size,
            random_state=42
        )

        # Create figure
        fig, ax = plt.subplots(
            figsize=(10, 6)
        )

        # Scatter plot
        sc = ax.scatter(
            s['duration_min'],
            s['students_count'],
            c=np.log1p(s['students_count']),
            cmap='viridis',
            s=50,
            alpha=0.65,
            edgecolors='none'
        )

        plt.colorbar(
            sc,
            ax=ax,
            label='log(1 + Students)'
        )

        # Regression line
        m, b, r, _, _ = stats.linregress(
            s['duration_min'],
            s['students_count']
        )

        xr = np.linspace(
            s['duration_min'].min(),
            s['duration_min'].max(),
            100
        )

        ax.plot(
            xr,
            m * xr + b,
            color=ORANGE,
            lw=2,
            label=f'r = {r:.2f}'
        )

        ax.set_xlabel('Course Duration (minutes)')
        ax.set_ylabel('Students')

        ax.set_title(
            'Skillshare — Duration vs Students',
            fontweight='bold'
        )

        ax.legend()
        ax.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

else:

    print("Required columns missing")

# ── 6.3 Duration distribution by instructor ─────────────────────────────

required_cols = {'instructor', 'duration_min'}

if required_cols.issubset(skillshare.columns):

    # Remove missing rows
    temp_df = skillshare.dropna(
        subset=['instructor', 'duration_min']
    )

    # Keep valid durations
    temp_df = temp_df[
        temp_df['duration_min'] > 0
    ]

    # Top instructors only
    top_instructors = (
        temp_df['instructor']
        .value_counts()
        .head(8)
        .index
    )

    temp_df = temp_df[
        temp_df['instructor'].isin(top_instructors)
    ]

    # Prepare data
    instructors = top_instructors.tolist()

    data_d = [
        temp_df[
            temp_df['instructor'] == c
        ]['duration_min'].values
        for c in instructors
    ]

    # Create figure
    fig, ax = plt.subplots(
        figsize=(12, 6)
    )

    # Boxplot
    bp = ax.boxplot(
        data_d,
        labels=instructors,
        patch_artist=True,
        notch=False,
        medianprops=dict(
            color='white',
            lw=2
        )
    )

    # Colors
    box_colors = plt.cm.Set3(
        np.linspace(0, 1, len(instructors))
    )

    for patch, color in zip(bp['boxes'], box_colors):

        patch.set_facecolor(color)
        patch.set_alpha(0.65)

    # Jitter strip
    for i, data in enumerate(data_d, 1):

        jitter = np.random.normal(
            i,
            0.07,
            size=len(data)
        )

        ax.scatter(
            jitter,
            data,
            alpha=0.15,
            s=8,
            color='black'
        )

    ax.set_xticklabels(
        instructors,
        rotation=25,
        ha='right'
    )

    ax.set_ylabel('Duration (minutes)')

    ax.set_title(
        'Skillshare — Course Duration by Instructor',
        fontweight='bold'
    )

    ax.grid(
        axis='y',
        alpha=0.3
    )

    plt.tight_layout()
    plt.show()

else:

    print("Required columns missing")

"""#Cross Platform Comparision"""

# ── 7.1  Radar / spider chart ─────────────────────────────────────────────
import matplotlib.patches as mpatches

categories_radar = ['Avg Rating', 'Content Depth', 'Certification', 'Engagement', 'Breadth', 'Accessibility']
N = len(categories_radar)
angles = [n/float(N)*2*np.pi for n in range(N)]
angles += angles[:1]

platform_scores = {
    'Coursera':   [0.80, 0.65, 0.95, 0.70, 0.72, 0.60],
    'Udemy':      [0.78, 0.80, 0.55, 0.90, 0.95, 0.85],
    'Skillshare': [0.83, 0.55, 0.20, 0.85, 0.65, 0.92],
}

fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))
ax.set_facecolor('#1a1d27')
ax.set_theta_offset(np.pi/2); ax.set_theta_direction(-1)
ax.set_xticks(angles[:-1])
ax.set_xticklabels(categories_radar, fontsize=11)
ax.set_ylim(0, 1)
ax.yaxis.set_tick_params(labelsize=8)

for (name, scores), color in zip(platform_scores.items(), [BLUE, ORANGE, GREEN]):
    vals = scores + scores[:1]
    ax.plot(angles, vals, color=color, lw=2.5, label=name)
    ax.fill(angles, vals, color=color, alpha=0.1)

ax.set_title('Platform Comparison — Radar Chart', fontweight='bold', pad=20)
ax.legend(loc='upper right', bbox_to_anchor=(1.25, 1.1))
plt.tight_layout(); plt.show()

# ── 7.2  Rating comparison — violin across platforms ──────────────────────
fig, ax = plt.subplots(figsize=(10, 5))

rating_data, labels_v, colors_v = [], [], []
for df, name, color in [(coursera,'Coursera',BLUE),(udemy,'Udemy',ORANGE),(skillshare,'Skillshare',GREEN)]:
    if 'rating' in df.columns:
        rating_data.append(df['rating'].dropna().values)
        labels_v.append(name); colors_v.append(color)

parts = ax.violinplot(rating_data, showmedians=True, showextrema=True)
for pc, col in zip(parts['bodies'], colors_v):
    pc.set_facecolor(col); pc.set_alpha(0.65)
parts['cmedians'].set_color('white'); parts['cmedians'].set_lw(2)
ax.set_xticks(range(1, len(labels_v)+1)); ax.set_xticklabels(labels_v, fontsize=12)
ax.set_ylabel('Rating'); ax.set_ylim(0, 5.5)
ax.set_title('Rating Distribution by Platform (violin)', fontweight='bold')
ax.grid(axis='y', alpha=0.3)
plt.tight_layout(); plt.show()

# ── 7.3 Student/Enrollment comparison across platforms ──────────────────

fig, ax = plt.subplots(figsize=(11, 6))

student_data = []
labels_v = []
colors_v = []

# ── Coursera ─────────────────────────────────

if 'num_students' in coursera.columns:

    coursera_students = pd.to_numeric(
        coursera['num_students'],
        errors='coerce'
    ).dropna()

    coursera_students = coursera_students[
        coursera_students > 0
    ]

    if len(coursera_students) > 0:

        student_data.append(
            np.log1p(coursera_students.values)
        )

        labels_v.append('Coursera')
        colors_v.append(BLUE)

# ── Udemy ───────────────────────────────────

if 'num_students' in udemy.columns:

    udemy_students = pd.to_numeric(
        udemy['num_students'],
        errors='coerce'
    ).dropna()

    udemy_students = udemy_students[
        udemy_students > 0
    ]

    if len(udemy_students) > 0:

        student_data.append(
            np.log1p(udemy_students.values)
        )

        labels_v.append('Udemy')
        colors_v.append(ORANGE)

# ── Skillshare ──────────────────────────────

if 'students_count' in skillshare.columns:

    skillshare_students = pd.to_numeric(
        skillshare['students_count'],
        errors='coerce'
    ).dropna()

    skillshare_students = skillshare_students[
        skillshare_students > 0
    ]

    if len(skillshare_students) > 0:

        student_data.append(
            np.log1p(skillshare_students.values)
        )

        labels_v.append('Skillshare')
        colors_v.append(GREEN)

# ── Plot violin ─────────────────────────────

if len(student_data) > 0:

    parts = ax.violinplot(
        student_data,
        showmedians=True,
        showextrema=True
    )

    # Colors
    for pc, col in zip(parts['bodies'], colors_v):

        pc.set_facecolor(col)
        pc.set_alpha(0.65)

    # Median styling
    parts['cmedians'].set_color('white')
    parts['cmedians'].set_linewidth(2)

    # Axis labels
    ax.set_xticks(
        range(1, len(labels_v) + 1)
    )

    ax.set_xticklabels(
        labels_v,
        fontsize=12
    )

    ax.set_ylabel('log(1 + Students / Enrollment)')

    ax.set_title(
        'Student Distribution by Platform (Violin Plot)',
        fontweight='bold'
    )

    ax.grid(
        axis='y',
        alpha=0.3
    )

    plt.tight_layout()
    plt.show()

else:

    print("No valid student/enrollment data found")

# ── 7.2 Enrollment comparison across platforms ──────────────────────────

fig, ax = plt.subplots(figsize=(11, 6))

student_data = []
labels_v = []
colors_v = []

# Helper function
def get_numeric_series(df, possible_cols):

    for col in possible_cols:

        if col in df.columns:

            series = pd.to_numeric(
                df[col],
                errors='coerce'
            ).dropna()

            series = series[series > 0]

            if len(series) > 0:
                return series

    return None

# ── Coursera ─────────────────────────────────

coursera_series = get_numeric_series(
    coursera,
    [
        'num_students',
        'enrolled',
        'students',
        'num_enrolled'
    ]
)

if coursera_series is not None:

    student_data.append(
        np.log1p(coursera_series.values)
    )

    labels_v.append('Coursera')
    colors_v.append(BLUE)

# ── Udemy ───────────────────────────────────

udemy_series = get_numeric_series(
    udemy,
    [
        'num_students',
        'number_of_viewers'
    ]
)

if udemy_series is not None:

    student_data.append(
        np.log1p(udemy_series.values)
    )

    labels_v.append('Udemy')
    colors_v.append(ORANGE)

# ── Skillshare ──────────────────────────────

skillshare_series = get_numeric_series(
    skillshare,
    [
        'students_count',
        'students'
    ]
)

if skillshare_series is not None:

    student_data.append(
        np.log1p(skillshare_series.values)
    )

    labels_v.append('Skillshare')
    colors_v.append(GREEN)

# ── Plot ────────────────────────────────────

if len(student_data) > 0:

    parts = ax.violinplot(
        student_data,
        showmedians=True,
        showextrema=True
    )

    # Colors
    for pc, col in zip(parts['bodies'], colors_v):

        pc.set_facecolor(col)
        pc.set_alpha(0.65)

    # Median line
    parts['cmedians'].set_color('white')
    parts['cmedians'].set_linewidth(2)

    # Labels
    ax.set_xticks(
        range(1, len(labels_v) + 1)
    )

    ax.set_xticklabels(
        labels_v,
        fontsize=12
    )

    ax.set_ylabel(
        'log(1 + Students / Enrollment)'
    )

    ax.set_title(
        'Enrollment Distribution by Platform',
        fontweight='bold'
    )

    ax.grid(
        axis='y',
        alpha=0.3
    )

    plt.tight_layout()
    plt.show()

else:

    print("No valid enrollment data found")

# ── 7.3 Platform popularity distribution ────────────────────────────────
import re
fig, ax = plt.subplots(figsize=(12, 7))

# Helper function
def get_students_column(df):

    possible_cols = [
        'num_students',
        'enrolled',
        'students',
        'num_enrolled',
        'learners',
        'number_of_viewers'
    ]

    for col in possible_cols:

        if col in df.columns:
            return col

    return None
# ───────────────────────────────────────────
# Coursera
# ───────────────────────────────────────────

def parse_enrollment(value):

    if pd.isna(value):
        return np.nan

    value = str(value).lower().replace(',', '').strip()

    try:

        if 'm' in value:
            return float(value.replace('m', '')) * 1_000_000

        elif 'k' in value:
            return float(value.replace('k', '')) * 1_000

        else:
            return float(
                re.findall(r'[\d.]+', value)[0]
            )

    except:
        return np.nan

# Clean enrolled column
c_students = coursera['enrolled'].apply(parse_enrollment)

c_students = c_students.dropna()

c_students = c_students[
    c_students > 0
]

print("Coursera rows:", len(c_students))

if len(c_students) > 0:

    y = np.log1p(
        c_students.sample(
            min(300, len(c_students)),
            random_state=42
        )
    )

    x = np.random.normal(
        1,
        0.05,
        size=len(y)
    )

    ax.scatter(
        x,
        y,
        alpha=0.35,
        s=40,
        color=BLUE,
        label='Coursera'
    )
# ───────────────────────────────────────────
# Udemy
# ───────────────────────────────────────────

u_col = get_students_column(udemy)

if u_col:

    u_students = pd.to_numeric(
        udemy[u_col],
        errors='coerce'
    ).dropna()

    u_students = u_students[
        u_students > 0
    ]

    print("Udemy column:", u_col)
    print("Udemy rows:", len(u_students))

    if len(u_students) > 0:

        y = np.log1p(
            u_students.sample(
                min(300, len(u_students)),
                random_state=42
            )
        )

        x = np.random.normal(
            2,
            0.05,
            size=len(y)
        )

        ax.scatter(
            x,
            y,
            alpha=0.35,
            s=40,
            color=ORANGE,
            label='Udemy'
        )

# ───────────────────────────────────────────
# Skillshare
# ───────────────────────────────────────────

if 'students_count' in skillshare.columns:

    s_students = pd.to_numeric(
        skillshare['students_count'],
        errors='coerce'
    ).dropna()

    s_students = s_students[
        s_students > 0
    ]

    print("Skillshare rows:", len(s_students))

    if len(s_students) > 0:

        y = np.log1p(
            s_students.sample(
                min(300, len(s_students)),
                random_state=42
            )
        )

        x = np.random.normal(
            3,
            0.05,
            size=len(y)
        )

        ax.scatter(
            x,
            y,
            alpha=0.35,
            s=40,
            color=GREEN,
            label='Skillshare'
        )

# ───────────────────────────────────────────
# Styling
# ───────────────────────────────────────────

ax.set_xticks([1, 2, 3])

ax.set_xticklabels([
    'Coursera',
    'Udemy',
    'Skillshare'
])

ax.set_ylabel(
    'log(1 + Students / Enrollment)'
)

ax.set_title(
    'Platform Popularity Distribution',
    fontweight='bold'
)

ax.grid(
    axis='y',
    alpha=0.3
)

ax.legend()

plt.tight_layout()
plt.show()

# ── 7.4 Correlation heatmap per platform ────────────────────────────────

fig, axes = plt.subplots(
    1,
    3,
    figsize=(20, 6)
)

datasets = [
    (coursera, 'Coursera'),
    (udemy, 'Udemy'),
    (skillshare, 'Skillshare')
]

for ax, (df, name) in zip(axes, datasets):

    temp_df = df.copy()

    # Try converting object columns to numeric
    for col in temp_df.columns:

        if temp_df[col].dtype == 'object':

            cleaned = (
                temp_df[col]
                .astype(str)
                .str.replace(',', '', regex=False)
                .str.extract(r'([\d.]+)')[0]
            )

            converted = pd.to_numeric(
                cleaned,
                errors='coerce'
            )

            # Keep conversion only if enough numeric values exist
            if converted.notna().sum() > len(df) * 0.3:

                temp_df[col] = converted

    # Select numeric columns
    num_df = temp_df.select_dtypes(
        include='number'
    )

    # Remove fully empty columns
    num_df = num_df.dropna(
        axis=1,
        how='all'
    )

    # Remove constant columns
    num_df = num_df.loc[
        :,
        num_df.nunique() > 1
    ]

    # Check if enough columns exist
    if num_df.shape[1] < 2:

        ax.text(
            0.5,
            0.5,
            'Not enough numeric data',
            ha='center',
            va='center',
            fontsize=14
        )

        ax.set_title(
            f'{name} — Correlation Matrix',
            fontweight='bold'
        )

        ax.axis('off')

        continue

    # Correlation
    corr = num_df.corr()

    # Mask upper triangle
    mask = np.triu(
        np.ones_like(
            corr,
            dtype=bool
        )
    )

    # Heatmap
    sns.heatmap(
        corr,
        ax=ax,
        mask=mask,
        annot=True,
        fmt='.2f',
        cmap='coolwarm',
        center=0,
        linewidths=0.4,
        linecolor='#0f1117',
        vmin=-1,
        vmax=1,
        cbar_kws={'shrink': 0.8}
    )

    ax.set_title(
        f'{name} — Correlation Matrix',
        fontweight='bold'
    )

plt.tight_layout()
plt.show()

"""Plotly Charts"""

print(coursera.columns.tolist())

print(coursera['enrolled'].head(20).tolist())

# ── 8.1 Plotly Treemap — Coursera organizations by reviews ─────────────

temp_df = coursera.copy()

# Clean num_reviews
temp_df['reviews_clean'] = (
    temp_df['num_reviews']
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.extract(r'(\d+\.?\d*)')[0]
)

temp_df['reviews_clean'] = pd.to_numeric(
    temp_df['reviews_clean'],
    errors='coerce'
)

# Remove invalid rows
temp_df = temp_df.dropna(
    subset=[
        'Organization',
        'reviews_clean'
    ]
)

# Keep positive values
temp_df = temp_df[
    temp_df['reviews_clean'] > 0
]

print("Valid rows:", len(temp_df))

# Top organizations
top_orgs = (
    temp_df['Organization']
    .value_counts()
    .head(15)
    .index
)

temp_df = temp_df[
    temp_df['Organization'].isin(top_orgs)
]

# Grouping
tm = (
    temp_df
    .groupby('Organization')
    .agg(
        courses=('title', 'count'),
        avg_reviews=('reviews_clean', 'mean')
    )
    .reset_index()
)

# Treemap
fig = px.treemap(
    tm,
    path=['Organization'],
    values='courses',
    color='avg_reviews',
    color_continuous_scale='Blues',
    title='Coursera — Organization Treemap (by Reviews)',
    template='plotly_white'
)

fig.update_layout(
    margin=dict(
        t=50,
        l=10,
        r=10,
        b=10
    )
)

fig.show()

# ── 8.2 Plotly Scatter — Udemy price vs viewers ────────────────────────

temp_df = udemy.copy()

# Helper to find columns ignoring case
def find_col(df, target):

    for col in df.columns:

        if col.lower() == target.lower():

            return col

    return None

# Detect columns
price_col = find_col(temp_df, 'price')
viewer_col = find_col(temp_df, 'number of viewers')
rating_col = find_col(temp_df, 'rating')
category_col = find_col(temp_df, 'category')
title_col = find_col(temp_df, 'title')

print(price_col)
print(viewer_col)
print(rating_col)
print(category_col)
print(title_col)

# Continue only if columns exist
if all([
    price_col,
    viewer_col,
    rating_col,
    category_col,
    title_col
]):

    # Clean price
    temp_df['price_clean'] = pd.to_numeric(
        temp_df[price_col],
        errors='coerce'
    )

    # Clean viewers
    temp_df['viewers_clean'] = (
        temp_df[viewer_col]
        .astype(str)
        .str.replace(',', '', regex=False)
        .str.extract(r'(\d+\.?\d*)')[0]
    )

    temp_df['viewers_clean'] = pd.to_numeric(
        temp_df['viewers_clean'],
        errors='coerce'
    )

    # Clean rating
    temp_df['rating_clean'] = pd.to_numeric(
        temp_df[rating_col],
        errors='coerce'
    )

    # Remove invalid rows
    temp_df = temp_df.dropna(
        subset=[
            'price_clean',
            'viewers_clean',
            'rating_clean'
        ]
    )

    temp_df = temp_df[
        temp_df['viewers_clean'] > 0
    ]

    print("Valid rows:", len(temp_df))

    # Sample
    sample_p = temp_df.sample(
        min(800, len(temp_df)),
        random_state=7
    )

    # Plot
    fig = px.scatter(
        sample_p,
        x='price_clean',
        y='viewers_clean',
        size='rating_clean',
        color=category_col,
        hover_name=title_col,
        size_max=30,
        opacity=0.65,
        log_y=True,
        title='Udemy — Price vs Viewers',
        template='plotly_white'
    )

    fig.update_layout(
        xaxis_title='Price',
        yaxis_title='Number of Viewers'
    )

    fig.show()

else:

    print("Required columns missing")

# Clean column names
udemy.columns = (
    udemy.columns
    .str.strip()
    .str.lower()
)

print(udemy.columns.tolist())

fig = go.Figure()

for df, name, color in [(coursera,'Coursera',BLUE),(udemy,'Udemy',ORANGE),(skillshare,'Skillshare',GREEN)]:
    if 'rating' in df.columns:
        print(name, df.shape)
        print(df['rating'].head() if 'rating' in df.columns else "NO RATING COLUMN")
        r = df['rating'].dropna()
        q1, med, q3 = r.quantile(0.25), r.median(), r.quantile(0.75)
        fig.add_trace(go.Bar(
            name=name, x=[name],
            y=[med], error_y=dict(type='data', symmetric=False,
                                   array=[q3-med], arrayminus=[med-q1]),
            marker_color=color, width=0.35
        ))

fig.update_layout(
    title='Platform Rating — Median ± IQR',
    yaxis_title='Rating', template='plotly_dark',
    showlegend=True, barmode='group'
)
fig.show()

